# NumPy

In [1]:
import numpy as np

### np.array()

In [2]:
l = [1, 2, 3, 4, 5]

In [3]:
npa = np.array(l)

In [4]:
type(l), type(npa)

(list, numpy.ndarray)

In [5]:
npa

array([1, 2, 3, 4, 5])

In [6]:
npa.shape

(5,)

In [7]:
l.append('string')

In [8]:
npa = np.array(l)

In [9]:
npa

array(['1', '2', '3', '4', '5', 'string'], dtype='<U11')

In [10]:
l1 = [1, 4, 16]

In [11]:
l + l1

[1, 2, 3, 4, 5, 'string', 1, 4, 16]

In [12]:
np.array(l + l1)

array(['1', '2', '3', '4', '5', 'string', '1', '4', '16'], dtype='<U11')

In [13]:
l = [[1, 2], [3, 4], [5, 6]]

In [14]:
npa2d = np.array(l)

In [15]:
npa2d = np.array(l, dtype='float')

In [16]:
npa2d

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [17]:
npa2d = np.array(l).astype('str')

In [18]:
npa2d

array([['1', '2'],
       ['3', '4'],
       ['5', '6']], dtype='<U11')

### `np.nan` and `np.inf`

In [19]:
np.nan == np.nan

False

In [20]:
None == None

True

In [21]:
np.inf == np.inf

True

In [22]:
npa2d = npa2d.astype("int")

In [23]:
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
# npa2d[0, 0] = np.nan # Throws error
npa2d = npa2d.astype("float")
npa2d[0, 0] = np.nan # No longer throws error
npa2d

array([[nan,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [25]:
npa2d[2, 1] = np.inf

In [26]:
flag = np.isnan(npa2d)

In [27]:
flag

array([[ True, False],
       [False, False],
       [False, False]])

In [28]:
flag = np.isinf(npa2d)
flag

array([[False, False],
       [False, False],
       [False,  True]])

### Statistical Operations

In [29]:
# mean(mean), variance(var), standard deviation(std), median(med)

In [30]:
npa2d.mean()

nan

In [31]:
npa2d[0, 0] = 1
npa2d[2, 1] = 6
npa2d = npa2d.astype("int")
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
npa2d.mean()

3.5

In [33]:
npa2d.var()

2.9166666666666665

In [34]:
npa2d.std()

1.707825127659933

In [35]:
npa2d.max()

6

In [36]:
npa2d.min()

1

In [37]:
np.median(npa2d)

3.5

### Shape, Reshape, Ravel

In [38]:
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
npa2d.shape

(3, 2)

In [40]:
# npa2d.reshape(1, 3) # Will throw since size of reshape does not equal the original shape.
npa2d.reshape(1, 6)


array([[1, 2, 3, 4, 5, 6]])

In [41]:
npa2d.reshape(1, 6).ravel()

array([1, 2, 3, 4, 5, 6])

In [42]:
npa2d.flatten()

array([1, 2, 3, 4, 5, 6])

In [43]:
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

### Sequence, Repetitions, and Random Numbers

In [44]:
np.arange(1, 5) # np a-range -> Array Range

array([1, 2, 3, 4])

In [45]:
np.arange(1, 5, dtype = "float") # np a-range -> Array Range

array([1., 2., 3., 4.])

In [46]:
np.arange(0, 27, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [47]:
np.linspace(1, 20, 3) # start, end, number of numbers equally spaced from one another (linear space)

array([ 1. , 10.5, 20. ])

In [48]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [49]:
np.logspace(1, 50, 10) # start, end, number of nubmer within a log spacing

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [50]:
np.zeros([5, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.ones([5, 5]).astype("int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [52]:
np.tile([1, 2], 3) # Repeat a pattern a certain number of times

array([1, 2, 1, 2, 1, 2])

In [53]:
np.repeat([1, 2], 3)

array([1, 1, 1, 2, 2, 2])

In [54]:
np.random.rand(3, 3) # 3 by 3 grid of random numbers between 0 and 1

array([[4.64537212e-01, 1.53339091e-01, 6.83229361e-01],
       [2.63378832e-01, 3.76119653e-01, 3.56385063e-01],
       [6.55901072e-04, 8.35522957e-01, 6.94060183e-01]])

In [55]:
np.random.randint(0, 10, [5, 5])

array([[0, 1, 5, 3, 3],
       [2, 3, 7, 0, 5],
       [6, 0, 9, 8, 8],
       [8, 0, 0, 2, 9],
       [0, 7, 6, 3, 9]])

In [56]:
np.random.randint(0, 10)

1

In [57]:
np.random.seed(1)

In [58]:
np.random.randint(0, 100, [5,5])

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [20, 18, 84, 11, 28],
       [29, 14, 50, 68, 87]])

In [59]:
np.unique(npa2d)

array([1, 2, 3, 4, 5, 6])

In [60]:
np.unique(npa2d, return_counts=True) # Returns all numbers present in the array (only one member for duplicates). You can check the count by adding the return_counts arg

(array([1, 2, 3, 4, 5, 6]), array([1, 1, 1, 1, 1, 1], dtype=int64))

# Where()

In [61]:
arr = np.array([1,2,3,4,5,6,7,8])

In [62]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
indexs = np.where(arr > 3)
arr[indexs]

array([4, 5, 6, 7, 8])

In [68]:
arr>3

array([False, False, False,  True,  True,  True,  True,  True])

In [67]:
arr[arr>3]

array([4, 5, 6, 7, 8])

In [69]:
arr.max()

8

In [70]:
arr.argmax()

7

In [72]:
arr.min()

1

In [71]:
arr.argmin()

0

# File Read and Write

In [73]:
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
np.savetxt('npa2d.csv', npa2d, delimiter=',')

In [75]:
np.loadtxt('npa2d.csv', delimiter=',')

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [76]:
np.save('data.npy', npa2d)

In [77]:
np.load('data.npy')

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
np.savez('both.npz', arr, npa2d)

In [80]:
np.load('both.npz')

NpzFile 'both.npz' with keys: arr_0, arr_1

In [81]:
d = np.load('both.npz')

In [83]:
d['arr_0']

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
d['arr_1']

array([[1, 2],
       [3, 4],
       [5, 6]])

# Concatenate and Sorting

In [86]:
npa2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
np.concatenate([npa2d, npa2d], axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4],
       [5, 6]])

In [88]:
np.concatenate([npa2d, npa2d], axis = 1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6]])

In [90]:
# Both arrays need to be the same size for concatenate to work

In [91]:
np.vstack([npa2d, npa2d])

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4],
       [5, 6]])

In [92]:
np.hstack([npa2d, npa2d])

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6]])

In [93]:
npa = np.hstack([npa2d, npa2d])

In [94]:
npa.sort()

In [95]:
npa

array([[1, 1, 2, 2],
       [3, 3, 4, 4],
       [5, 5, 6, 6]])

# Working with Dates

In [96]:
d = np.datetime64('2024-04-19 12:00:00')

In [97]:
d

numpy.datetime64('2024-04-19T12:00:00')

In [98]:
d + 10

numpy.datetime64('2024-04-19T12:00:10')

In [99]:
oneday = np.timedelta64(1, 'D')

In [100]:
oneday

numpy.timedelta64(1,'D')

In [101]:
d + oneday

numpy.datetime64('2024-04-20T12:00:00')

In [102]:
oneminute = np.timedelta64(1, 'm')

In [103]:
d + oneminute

numpy.datetime64('2024-04-19T12:01:00')